### ISSUE TITLE
Крэш после возврата в инфо активити

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/android_gisapp#113]
Если зайти в инфо-активити объекта, затем в эбаут/настройки и вернуться обратно, то панель никак закрыть, кнопки следующая/предыдущая запись приводят к крэшу.

**Comment by BishopGIS** [comment]
Да, есть такое
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:359)
	at android.view.View.(View.java:3588)
	at android.view.View.(View.java:3683)
	at android.widget.TextView.(TextView.java:640)
	at android.widget.TextView.(TextView.java:635)
	at android.widget.TextView.(TextView.java:631)
	at android.widget.TextView.(TextView.java:627)
	at com.nextgis.mobile.AttributesFragment.setAttributes(AttributesFragment.java:138)
	at com.nextgis.mobile.AttributesFragment.selectItem(AttributesFragment.java:203)
	at com.nextgis.mobile.MapFragment$9.onMenuItemClick(MapFragment.java:833)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:738)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:596)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:145)
	at android.view.View.performClick(View.java:4781)
	at android.view.View$PerformClick.run(View.java:19873)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
