### ISSUE TITLE
Падение при работе со списком слоев

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#256]
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689612, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1562)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:3842)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3641)
	at com.nextgis.maplibui.fragment.ReorderedLayerView.onTouchEvent(ReorderedLayerView.java:371)
	at android.view.View.dispatchTouchEvent(View.java:8547)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at android.support.v4.app.BaseFragmentActivityDonut.dispatchTouchEvent(BaseFragmentActivityDonut.java)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
	at android.view.View.dispatchPointerEvent(View.java:8742)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3693)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3750)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3584)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5823)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5797)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5768)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5913)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:195)
	at android.app.ActivityThread.main(ActivityThread.java:5389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by BishopGIS** [comment]
Тут событие об изменении состава слоев видимо приходит не из основного потока. Видимо вызов notifyDataSetChanged надо делать через handler

**Comment by 4eRTuk** [comment]
Баг поймать так и не удалось, обернул все notifyDataSetChanged из событий в runOnUiThread.

**Comment by BishopGIS** [comment]
Ok, понаблюдаем.
