### ISSUE TITLE
Падение связанное с треками

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#257]
java.lang.NullPointerException
	at com.nextgis.maplibui.service.TrackerService.hasUnfinishedTracks(TrackerService.java:416)
	at com.nextgis.mobile.activity.MainActivity.onPrepareOptionsMenu(MainActivity.java:649)
	at android.app.Activity.onPreparePanel(Activity.java:2494)
	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:451)
	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:440)
	at android.support.v7.internal.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:268)
	at android.support.v7.internal.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
	at android.support.v7.internal.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:555)
	at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:448)
	at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:65)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:524)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:4787)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
	at dalvik.system.NativeStart.main(Native Method)

Последние
Сегодня, 22:36
Повторов за эту неделю 1
Повторов за все время 1
Версия приложения 2.2
Версия Android Android 4.1
Устройство Xperia V (LT25i)

**Comment by BishopGIS** [comment]
Fix in 7073aa6e3f4414a8f21450b631e1aeb11ae2f3ff
