### ISSUE TITLE
TrackLayer.initDB error

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#265]
Ошибки из маркета
```
java.lang.RuntimeException: Unable to get provider com.nextgis.maplib.datasource.LayerContentProvider: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.app.ActivityThread.installProvider(ActivityThread.java:5424)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4992)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4927)
	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5721)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:235)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:219)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:854)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:834)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:760)
	at com.nextgis.maplib.util.DatabaseContext.openOrCreateDatabase(DatabaseContext.java:75)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.nextgis.maplib.map.MapContentProviderHelper.getDatabase(MapContentProviderHelper.java:102)
	at com.nextgis.maplib.map.TrackLayer.initDB(TrackLayer.java:289)
	at com.nextgis.maplib.map.TrackLayer.<init>(TrackLayer.java:145)
	at com.nextgis.maplibui.mapui.TrackLayerUI.<init>(TrackLayerUI.java:48)
	at com.nextgis.mobile.MainApplication.checkTracksLayerExist(MainApplication.java:100)
	at com.nextgis.mobile.MainApplication.getMap(MainApplication.java:88)
	at com.nextgis.maplib.datasource.LayerContentProvider.onCreate(LayerContentProvider.java:52)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1702)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1665)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5421)
	... 11 more
```

и еще похожая

```
java.lang.RuntimeException: Unable to create application com.nextgis.mobile.MainApplication: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4594)
	at android.app.ActivityThread.access$1500(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:897)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:642)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:323)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:297)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:916)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:893)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:796)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:819)
	at com.nextgis.maplib.util.DatabaseContext.openOrCreateDatabase(DatabaseContext.java:75)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.nextgis.maplib.map.MapContentProviderHelper.getDatabase(MapContentProviderHelper.java:102)
	at com.nextgis.maplib.map.TrackLayer.initDB(TrackLayer.java:289)
	at com.nextgis.maplib.map.TrackLayer.<init>(TrackLayer.java:145)
	at com.nextgis.maplibui.mapui.TrackLayerUI.<init>(TrackLayerUI.java:48)
	at com.nextgis.mobile.MainApplication.checkTracksLayerExist(MainApplication.java:100)
	at com.nextgis.mobile.MainApplication.getMap(MainApplication.java:88)
	at com.nextgis.maplibui.GISApplication.onCreate(GISApplication.java:81)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4591)
	... 9 more
```

**Comment by 4eRTuk** [comment]
По идее ошибка возникает когда к базе происходит обращение из разных потоков и через разные подключения. У нас все в MapContentProviderHelper сосредоточено.

Возможно, из-за того, что MapContentProviderHelper получался через GISApplication, а не через static MapBase.getInstance.

Обернул еще openOrCreateDatabase, надо смотреть подробнее стэктрейсы, если ошибка будет повторяться.

**Comment by BishopGIS** [comment]
Вообще sqlite дожна позволять обращаться из разных потоков.

**Comment by 4eRTuk** [comment]
Да, но на запись через одно подключение.

**Comment by BishopGIS** [comment]
Возможно стоит треки вынести в отдельную БД - запись из сервиса, чтение из приложения.

**Comment by BishopGIS** [comment]
Хотя можно убрать запуск из отдельного процесса https://github.com/nextgis/android_maplibui/blob/master/src/main/AndroidManifest.xml#L113
Это будет проще.
