### ISSUE TITLE
Падение при правке геометрии

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#282]
```
java.lang.NullPointerException
	at com.nextgis.maplibui.overlay.EditLayerOverlay.fillGeometry(EditLayerOverlay.java:652)
	at com.nextgis.maplibui.overlay.EditLayerOverlay.addInnerRing(EditLayerOverlay.java:1089)
	at com.nextgis.maplibui.overlay.EditLayerOverlay$2.onMenuItemClick(EditLayerOverlay.java:943)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:3549)
	at android.view.View$PerformClick.run(View.java:14400)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:4945)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

```

```
java.lang.NullPointerException
	at com.nextgis.maplibui.overlay.EditLayerOverlay.addInnerRing(EditLayerOverlay.java:1085)
	at com.nextgis.maplibui.overlay.EditLayerOverlay$2.onMenuItemClick(EditLayerOverlay.java:943)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:3549)
	at android.view.View$PerformClick.run(View.java:14400)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:4945)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by BishopGIS** [comment]
Опять падения при редактировании.
```
java.lang.NullPointerException
	at com.nextgis.maplibui.overlay.EditLayerOverlay.isCurrentGeometryValid(EditLayerOverlay.java:1684)
	at com.nextgis.maplibui.overlay.EditLayerOverlay.setToolbar(EditLayerOverlay.java:856)
	at com.nextgis.mobile.fragment.MapFragment.setMode(MapFragment.java:195)
	at com.nextgis.mobile.fragment.MapFragment$2.onMenuItemClick(MapFragment.java:238)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:3549)
	at android.view.View$PerformClick.run(View.java:14400)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:4945)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.nextgis.maplib.datasource.GeoGeometry.getType()' on a null object reference
	at com.nextgis.maplibui.overlay.EditLayerOverlay.isCurrentGeometryValid(EditLayerOverlay.java:1684)
	at com.nextgis.maplibui.overlay.EditLayerOverlay.setToolbar(EditLayerOverlay.java:856)
	at com.nextgis.mobile.fragment.MapFragment.setMode(MapFragment.java:195)
	at com.nextgis.mobile.fragment.MapFragment$2.onMenuItemClick(MapFragment.java:238)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:5197)
	at android.view.View$PerformClick.run(View.java:20926)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by BishopGIS** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplibui.overlay.EditLayerOverlay$EditLayerCacheItem.setGeometry(com.nextgis.maplib.datasource.GeoGeometry)' on a null object reference
	at com.nextgis.maplibui.overlay.EditLayerOverlay.createNewGeometry(EditLayerOverlay.java:1208)
	at com.nextgis.maplibui.overlay.EditLayerOverlay.addGeometry(EditLayerOverlay.java:1156)
	at com.nextgis.maplibui.overlay.EditLayerOverlay$2.onMenuItemClick(EditLayerOverlay.java:937)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:5197)
	at android.view.View$PerformClick.run(View.java:20926)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```
