### ISSUE TITLE
Поворот экрана приводит к крэшу

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#297]
Заходим в настройки векторного слоя, поворачиваем экран, потом поворачиваем обратно - приложение вылетает. Если то же самое сделать на растровом слое ngw, то сбрасываются все подписи к контролам, а подписи к контролу с уровнями зума выглядят как `Small Text`.

**Comment by BishopGIS** [comment]
```
java.lang.RuntimeException: Unable to pause activity {com.nextgis.mobile/com.nextgis.maplibui.activity.VectorLayerSettingsActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3736)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3695)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4429)
	at android.app.ActivityThread.access$1000(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:822)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:2038)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:528)
	at com.nextgis.maplibui.activity.VectorLayerSettingsActivity.onPause(VectorLayerSettingsActivity.java:275)
	at android.app.Activity.performPause(Activity.java:6447)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1308)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3722)
	... 11 more
```

```
java.lang.RuntimeException: Unable to pause activity {com.nextgis.mobile/com.nextgis.maplibui.activity.VectorLayerSettingsActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2842)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2798)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3485)
	at android.app.ActivityThread.access$700(ActivityThread.java:134)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4744)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1157)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
	at com.nextgis.maplibui.activity.VectorLayerSettingsActivity.onPause(VectorLayerSettingsActivity.java:275)
	at android.app.Activity.performPause(Activity.java:5106)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1225)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2829)
	... 12 more
```

**Comment by BishopGIS** [comment]
Вот еще с Android 6
```
java.lang.RuntimeException: Unable to resume activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.location.ILocationManager$Stub$Proxy.getLastLocation(ILocationManager.java:717)
	at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1200)
	at com.nextgis.maplibui.fragment.CompassFragment.onCreate(CompassFragment.java:129)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:1942)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1040)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:452)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)
	at android.app.Activity.performResume(Activity.java:6351)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
	... 10 more
```
