### ISSUE TITLE
Не хватате памяти

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#298]
Галерея фоток вылетает. возможно превьюхи стоит делать и их показывать. А большую только при просмотре на весь экран.

```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:529)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:302)
	at com.keenfin.easypicker.PhotoPicker.getBitmap(PhotoPicker.java:201)
	at com.keenfin.easypicker.PreviewActivity$PreviewFragment.onCreateView(PreviewActivity.java:83)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2176)
	at android.view.View.measure(View.java:15518)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1874)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1089)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1265)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by NikitaFeodonit** [comment]
Посмотрите, как сделано в Compilink'е. Там на каждом этапе преобразования исходной фотографии к миниатюре старался отслеживать освобождение памяти.

**Comment by BishopGIS** [comment]
Опять воспроизводится:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:529)
	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:302)
	at com.keenfin.easypicker.BitmapUtil.getBitmap(BitmapUtil.java:26)
	at com.keenfin.easypicker.BitmapWorkerTask.doInBackground(BitmapWorkerTask.java:30)
	at com.keenfin.easypicker.BitmapWorkerTask.doInBackground(BitmapWorkerTask.java:17)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 4 more
```
