### ISSUE TITLE
Падение при выборе слоя в НГВ

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#322]
Кажется еще был поворот экрана.
```
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
	at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:204)
	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:402)
	at android.view.View.measure(View.java:17331)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5376)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2548)
	at android.view.View.measure(View.java:17331)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2279)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1393)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1592)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6540)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
	at android.view.Choreographer.doCallbacks(Choreographer.java:613)
	at android.view.Choreographer.doFrame(Choreographer.java:583)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by 4eRTuk** [comment]
Интересный баг. При создании диалога с заданной темой через appcomat, происходит краш при восстановлении. Пока вернул диалоги без тем.
