### ISSUE TITLE
Падение на Андроид 3

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#323]
```
java.lang.IllegalStateException: ActionBarContextView can only be used with android:layout_width="match_parent" (or fill_parent)
	at com.android.internal.widget.ActionBarContextView.onMeasure(ActionBarContextView.java:257)
	at android.view.View.measure(View.java:10828)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1284)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:613)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:519)
	at android.view.View.measure(View.java:10828)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4351)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:267)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:1910)
	at android.view.View.measure(View.java:10828)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:913)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:2040)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:132)
	at android.app.ActivityThread.main(ActivityThread.java:4139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
	at dalvik.system.NativeStart.main(Native Method)

```

OS: 	Android 3.2.1 - API 13
Device: 	SHARP - A01SH
Screen: 	976 x 600 (160 dpi)

**Comment by 4eRTuk** [comment]
А есть девайс с API 13, на котором можно поотлавливать более подробно? В студии почему-то нет SDK для этой версии, чтобы эмулятор поставить.

**Comment by BishopGIS** [comment]
Да, действительно нет SDK. Девайса тоже.

**Comment by BishopGIS** [comment]
Давно ошибок не приходило. Закрываю.
