### ISSUE TITLE
Поворот экрана приводи к падению

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#335]
При открытом диалоге выбора слоев НГВ поворот экрана приводит к падению
```
02-21 17:07:26.463 25308-25308/? E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.nextgis.mobile, PID: 25308
 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
  at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:172)
  at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:317)
  at android.view.View.measure(View.java:16521)
  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
  at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2552)
  at android.view.View.measure(View.java:16521)
  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
  at android.view.Choreographer.doCallbacks(Choreographer.java:574)
  at android.view.Choreographer.doFrame(Choreographer.java:544)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5139)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
Duplicate #322
