### ISSUE TITLE
Падение при просмотре атрибутов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#347]
Стэктрейс:
```
java.lang.RuntimeException: Unable to resume activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3003)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3032)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at com.nextgis.mobile.fragment.AttributesFragment.setAttributes(AttributesFragment.java:218)
	at com.nextgis.mobile.fragment.AttributesFragment.onResume(AttributesFragment.java:151)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2008)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1119)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2063)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:187)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:462)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:451)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)
	at android.app.Activity.performResume(Activity.java:5435)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2989)
	... 10 more
```

```
java.lang.NullPointerException
	at com.nextgis.maplibui.util.ControlHelper.setEnabled(ControlHelper.java:67)
	at com.nextgis.mobile.fragment.AttributesFragment.checkNearbyItems(AttributesFragment.java:425)
	at com.nextgis.mobile.fragment.AttributesFragment.setAttributes(AttributesFragment.java:326)
	at com.nextgis.mobile.fragment.AttributesFragment.setSelectedFeature(AttributesFragment.java:197)
	at com.nextgis.mobile.fragment.MapFragment.setMode(MapFragment.java:425)
	at com.nextgis.mobile.fragment.MapFragment$4.onMenuItemClick(MapFragment.java:380)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
Fix in 41b929fdda63cd27f700555600e08e94ab808648
