### ISSUE TITLE
Падение при просмотре карты

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#348]
Стэктрейс
```
java.lang.NullPointerException
	at android.graphics.Canvas.<init>(Canvas.java:136)
	at com.nextgis.maplib.display.GISDisplay.setSize(GISDisplay.java:152)
	at com.nextgis.maplib.map.MapDrawable.setViewSize(MapDrawable.java:127)
	at com.nextgis.maplibui.mapui.MapViewBase.onSizeChanged(MapViewBase.java:153)
	at android.view.View.sizeChange(View.java:15253)
	at android.view.View.setFrame(View.java:15226)
	at android.view.View.layout(View.java:15114)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
	at android.view.View.layout(View.java:15125)
	at android.view.ViewGroup.layout(ViewGroup.java:4862)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2323)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2029)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
Fix in 41b929fdda63cd27f700555600e08e94ab808648
