### ISSUE TITLE
Падение при записи обходом

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#349]
Стэктрейс:
```
java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:667)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1556)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
	at com.nextgis.maplibui.overlay.EditLayerOverlay.stopGeometryByWalk(EditLayerOverlay.java:743)
	at com.nextgis.mobile.fragment.MapFragment$2.onMenuItemClick(MapFragment.java:325)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:180)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:761)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4463)
	at android.view.View$PerformClick.run(View.java:18770)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
Fix in 41b929fdda63cd27f700555600e08e94ab808648
