### ISSUE TITLE
Падение при отрисовке

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#362]
```
java.lang.NullPointerException
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1083)
	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:811)
	at com.nextgis.maplib.display.GISDisplay.draw(GISDisplay.java:306)
	at com.nextgis.maplib.map.MapDrawable.draw(MapDrawable.java:89)
	at com.nextgis.maplibui.mapui.MapView.onDraw(MapView.java:146)
	at com.nextgis.maplibui.mapui.MapViewOverlays.onDraw(MapViewOverlays.java:81)
	at android.view.View.draw(View.java:14728)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getHardwareLayerDisplayList(View.java:13620)
	at android.view.View.getHardwareLayer(View.java:13298)
	at android.view.View.getDisplayList(View.java:13548)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.draw(View.java:14739)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at android.view.View.getDisplayList(View.java:13580)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.View.draw(View.java:14430)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2423)
	at android.view.View.draw(View.java:14739)
	at android.widget.FrameLayout.draw(FrameLayout.java:534)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2403)
	at android.view.View.getDisplayList(View.java:13588)
	at android.view.View.getDisplayList(View.java:13635)
	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1627)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1506)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2728)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2593)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5333)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by BishopGIS** [comment]
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplib.map.VectorLayer.showFeature(long)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4730)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4773)
	at android.app.ActivityThread.access$1500(ActivityThread.java:218)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6914)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplib.map.VectorLayer.showFeature(long)' on a null object reference
	at com.nextgis.mobile.fragment.MapFragment.onActivityResult(MapFragment.java:292)
	at com.nextgis.mobile.activity.MainActivity.onActivityResult(MainActivity.java:427)
	at android.app.Activity.dispatchActivityResult(Activity.java:6866)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4726)
	... 10 more
```
