### ISSUE TITLE
Падение при добавлении подложки из QMSS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#383]
Если нет интернета или оборвалось подключение, то приложение падает.
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:299)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.NullPointerException
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
	at org.json.JSONArray.<init>(JSONArray.java:87)
	at org.json.JSONArray.<init>(JSONArray.java:103)
	at com.nextgis.maplibui.dialog.CreateFromQMSLayerDialog$LoadLayersList.doInBackground(CreateFromQMSLayerDialog.java:245)
	at com.nextgis.maplibui.dialog.CreateFromQMSLayerDialog$LoadLayersList.doInBackground(CreateFromQMSLayerDialog.java:238)
	at android.os.AsyncTask$2.call(AsyncTask.java:287)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	... 4 more
```

**Comment by 4eRTuk** [comment]
Fix in 6975c17
