### ISSUE TITLE
Падение при resume

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#391]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ProgressBar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/menu_refresh. Make sure other views do not use the same id.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3951)
	at android.app.ActivityThread.access$900(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1299)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5234)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.widget.ProgressBar$SavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/menu_refresh. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:13099)
	at android.widget.TextView.onRestoreInstanceState(TextView.java:3635)
	at android.view.View.dispatchRestoreInstanceState(View.java:13075)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2657)
	at android.view.View.restoreHierarchyState(View.java:13053)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1747)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1017)
	at android.app.Activity.performRestoreInstanceState(Activity.java:989)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
	... 12 more
```

**Comment by BishopGIS** [comment]
Опять при resume падение
```
java.lang.RuntimeException: Unable to resume activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.NumberFormatException: Invalid int: "??.????"
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2444)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2472)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1986)
	at android.app.ActivityThread.access$600(ActivityThread.java:123)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NumberFormatException: Invalid int: "??.????"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:375)
	at java.lang.Integer.parseInt(Integer.java:366)
	at java.lang.Integer.parseInt(Integer.java:332)
	at com.nextgis.mobile.fragment.MapFragment.onResume(MapFragment.java:1013)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2008)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1119)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2063)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:187)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:462)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:451)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)
	at android.app.Activity.performResume(Activity.java:4552)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2434)
	... 12 more
```

**Comment by BishopGIS** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplib.map.VectorLayer.setLocked(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:234)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplib.map.VectorLayer.setLocked(boolean)' on a null object reference
	at com.nextgis.mobile.fragment.MapFragment.setMode(MapFragment.java:449)
	at com.nextgis.mobile.fragment.MapFragment.onViewStateRestored(MapFragment.java:928)
	at android.support.v4.app.Fragment.restoreViewState(Fragment.java:475)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1105)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2053)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6302)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
	... 9 more
```
