### ISSUE TITLE
Падение при отрисовке TMS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#394]
```
java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
    at java.util.ArrayList.get(ArrayList.java:304)
    at com.nextgis.maplib.map.RemoteTMSLayer.getURLSubdomain(RemoteTMSLayer.java:308)
    at com.nextgis.maplib.map.RemoteTMSLayer.downloadTile(RemoteTMSLayer.java:124)
    at com.nextgis.maplib.map.RemoteTMSLayer$1.run(RemoteTMSLayer.java:172)
    at java.lang.Thread.run(Thread.java:856)
```

Похоже из-за многопоточности.

**Comment by 4eRTuk** [comment]
Duplicate #487

**Comment by BishopGIS** [comment]
Fix in https://github.com/nextgis/nextgis_datastore/ will be available in NGM3
