### ISSUE TITLE
Crash while changing layers order

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#399]
```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689671, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
    at android.widget.ListView.layoutChildren(ListView.java:1584)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:5685)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:5481)
    at com.nextgis.maplibui.fragment.ReorderedLayerView.onTouchEvent(ReorderedLayerView.java:371)
    at android.view.View.dispatchTouchEvent(View.java:9187)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2680)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
    at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5418)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2743)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3042)
    at android.support.v4.app.BaseFragmentActivityDonut.dispatchTouchEvent(BaseFragmentActivityDonut.java)
    at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2704)
    at android.view.View.dispatchPointerEvent(View.java:9397)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5052)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4890)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4347)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4400)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4366)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4492)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4374)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4549)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4347)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4400)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4366)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4374)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4347)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6948)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6821)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6792)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7038)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:143)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:6914)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```

**Comment by BishopGIS** [comment]
На последнем билде:
```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689672, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1572)
	at android.widget.AbsListView.onTouchMove(AbsListView.java:5345)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:5211)
	at com.nextgis.maplibui.fragment.ReorderedLayerView.onTouchEvent(ReorderedLayerView.java:372)
	at android.view.View.dispatchTouchEvent(View.java:8281)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2471)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2194)
	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5160)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2477)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2209)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2332)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1616)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2665)
	at android.support.v4.app.BaseFragmentActivityDonut.dispatchTouchEvent(BaseFragmentActivityDonut.java)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2280)
	at android.view.View.dispatchPointerEvent(View.java:8489)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4892)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4431)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4488)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4351)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4328)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6707)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6586)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6557)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6522)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6787)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:138)
	at android.os.Looper.loop(Looper.java:131)
	at android.app.ActivityThread.main(ActivityThread.java:5756)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by 4eRTuk** [comment]
Какие шаги для воспроизведения?

**Comment by BishopGIS** [comment]
Это из феи. Есть еще только информация об устройстве:
Android 4.4.4 - API 19 (samsung - SM-T365)

**Comment by 4eRTuk** [comment]
А предыдущие падения тоже с него только?

**Comment by BishopGIS** [comment]
Там 24 краша на 7 разных устройствах. Этот краш только на этом устройстве.

**Comment by 4eRTuk** [comment]
Duplicate #495

**Comment by BishopGIS** [comment]
Опять падение
```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689687, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1591)
	at android.widget.AbsListView.onLayout(AbsListView.java:2202)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1215)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2854)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5498)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by BishopGIS** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-5
	at java.util.ArrayList.get(ArrayList.java:310)
	at com.nextgis.maplib.map.LayerGroup.getLayer(LayerGroup.java:536)
	at com.nextgis.maplibui.fragment.LayersListAdapter.getItem(LayersListAdapter.java:153)
	at com.nextgis.maplibui.fragment.LayersListAdapter.getView(LayersListAdapter.java:179)
	at android.widget.AbsListView.obtainView(AbsListView.java:2698)
	at android.widget.ListView.makeAndAddView(ListView.java:1811)
	at android.widget.ListView.fillDown(ListView.java:697)
	at android.widget.ListView.fillSpecific(ListView.java:1360)
	at android.widget.ListView.layoutChildren(ListView.java:1619)
	at android.widget.AbsListView.onLayout(AbsListView.java:2549)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1215)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:15745)
	at android.view.ViewGroup.layout(ViewGroup.java:4867)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
	at android.view.Choreographer.doCallbacks(Choreographer.java:614)
	at android.view.Choreographer.doFrame(Choreographer.java:584)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by simgislab** [comment]
need test case or more concrete information, may be contact a user who experienced it
