### ISSUE TITLE
Вылет при чтении из GeoJSON

### ISSUE THREAD

**Issue by trolleway** [nextgis/android_gisapp#415]
Есть векторный точечный слой.
Экспортирую его как файл - получается zip
Добавляю векторный слой - этот же zip файл.

Приложение аварийно завершается. В трее Android остаётся висеть плашка "Обработка слоя"

**Comment by BishopGIS** [comment]
ZIP только для тайлового кэша и только для совместимости. Вообще его надо убрать.

**Comment by 4eRTuk** [comment]
@BishopGIS Максим просил сделать и для geojson в ZIP.
@trolleway Выложи пример слоя, у меня не воспроизводится.

**Comment by simgislab** [comment]
@4eRTuk а у меня внезапно заработал джейсон в zip, так и задумано? раньше же вроде не было

**Comment by simgislab** [comment]
Однако выпадение у меня воспроизвелось. Порядок таков:

1. Грузим https://github.com/nextgis/nextgisweb_demodata/raw/master/buildings.zip
2. Добавляем как локальный
3. Делимся самому себе (я пересохранил в downloads)
4. Пытаемся открыть пересохраненный файл (я изменил имя)

Начинается процесс импорта и приложение сразу выпадает. В процессах плашка про импорт.

**Comment by BishopGIS** [comment]
Вот стектрэйс
```
java.lang.NullPointerException: Attempt to read from field 'com.nextgis.maplib.datasource.GeoEnvelope com.nextgis.maplib.datasource.GeometryRTree$Node.mCoords' on a null object reference
	at com.nextgis.maplib.datasource.GeometryRTree.getRequiredExpansion(GeometryRTree.java:747)
	at com.nextgis.maplib.datasource.GeometryRTree.splitNode(GeometryRTree.java:495)
	at com.nextgis.maplib.datasource.GeometryRTree.insert(GeometryRTree.java:429)
	at com.nextgis.maplib.datasource.GeometryRTree.addItem(GeometryRTree.java:145)
	at com.nextgis.maplib.map.VectorLayer.cacheGeometryEnvelope(VectorLayer.java:587)
	at com.nextgis.maplib.map.VectorLayer.createFeatureBatch(VectorLayer.java:524)
	at com.nextgis.maplib.util.GeoJSONUtil.createLayerFromGeoJSONStream(GeoJSONUtil.java:423)
	at com.nextgis.maplib.map.VectorLayer.createFromGeoJson(VectorLayer.java:361)
	at com.nextgis.maplibui.service.LayerFillService$VectorLayerFillTask.execute(LayerFillService.java:385)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:248)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by 4eRTuk** [comment]
@simgislab я добавил чтение geojson из zip

**Comment by 4eRTuk** [comment]
Вылетает, если CRS указана в конце файла и не WGS.

**Comment by BishopGIS** [comment]
Ну в случае потокового парсера мы тут ничего не сделаем. Только сбойные фичи перехватывать, что бы не падало.

**Comment by 4eRTuk** [comment]
Я сделал сначала чтение СК, потом обработку фич. Иначе вся геометрия будет неверная.

**Comment by BishopGIS** [comment]
Это ты все в память грузишь? Так делать нельзя. В память весь geoJSON не влазит очень часто.

**Comment by 4eRTuk** [comment]
Нет, я JsonReader прогоняю два раза, при чтении СК пропускаю массив с фичами.

**Comment by BishopGIS** [comment]
А, ок.
