### ISSUE TITLE
Падение при загрузке GeoJSON

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#429]
Падение при чтении geojson
```
java.lang.OutOfMemoryError
	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:124)
	at java.lang.StringBuilder.append(StringBuilder.java:271)
	at android.util.JsonReader.nextString(JsonReader.java:907)
	at android.util.JsonReader.nextValue(JsonReader.java:705)
	at android.util.JsonReader.objectValue(JsonReader.java:688)
	at android.util.JsonReader.peek(JsonReader.java:347)
	at android.util.JsonReader.nextString(JsonReader.java:406)
	at com.nextgis.maplib.util.NGWUtil.readNGWFeature(NGWUtil.java:389)
	at com.nextgis.maplib.map.NGWVectorLayer.createFromNGW(NGWVectorLayer.java:494)
	at com.nextgis.maplibui.service.LayerFillService$NGWVectorLayerFillTask.execute(LayerFillService.java:636)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:248)
	at java.lang.Thread.run(Thread.java:856)
```

4.1.2 (16) памяти на устройстве 1Гб

**Comment by 4eRTuk** [comment]
Не знаю, как быстро решить эту проблему. Нужно думать над форматом передачи данных - JsonReader не может загрузить такую большую геометрию.

**Comment by BishopGIS** [comment]
Тут нужно потоковый парсер геомтерии уже делать. https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/NGWUtil.java#L389
Хотя вот это видимо (nextgis/nextgisweb#475) более простое решение.

Пока надо добавить throws OutOfMemoryError вот сюда https://github.com/nextgis/android_maplib/blob/master/src/main/java/com/nextgis/maplib/util/NGWUtil.java#L379, что бы не падала программа.
