### ISSUE TITLE
Падение при добавлении слоя из НГВ

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#437]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at com.nextgis.maplibui.service.LayerFillService$NGWVectorLayerFillTask.execute(LayerFillService.java:663)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:254)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by trolleway** [comment]
Слой: http://trolleway.nextgis.com/resource/151/feature/ (копия https://gist.github.com/trolleway/c77deee5102183c258bcaec436716ab3)

**Comment by trolleway** [comment]
И на этом падает: http://trolleway.nextgis.com/resource/53
и на этом: http://trolleway.nextgis.com/resource/21
