### ISSUE TITLE
Падение при загрузке данных из НГВ

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#451]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nextgis.maplib.datasource.GeometryRTree$Node.setParent(com.nextgis.maplib.datasource.GeometryRTree$Node)' on a null object reference
	at com.nextgis.maplib.datasource.GeometryRTree$Node.add(GeometryRTree.java:788)
	at com.nextgis.maplib.datasource.GeometryRTree.splitNode(GeometryRTree.java:477)
	at com.nextgis.maplib.datasource.GeometryRTree.insert(GeometryRTree.java:429)
	at com.nextgis.maplib.datasource.GeometryRTree.addItem(GeometryRTree.java:145)
	at com.nextgis.maplib.map.VectorLayer.cacheGeometryEnvelope(VectorLayer.java:625)
	at com.nextgis.maplib.map.VectorLayer.createFeatureBatch(VectorLayer.java:562)
	at com.nextgis.maplib.map.NGWVectorLayer.createFromNGW(NGWVectorLayer.java:505)
	at com.nextgis.maplibui.service.LayerFillService$NGWVectorLayerFillTask.execute(LayerFillService.java:673)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:253)
	at java.lang.Thread.run(Thread.java:818)
```

Если RTree напрягает, можно заменить на хранение bbox каждой фичи в полях minx, miny, maxx, maxy и обычным запросом получать записи.
WHERE minx <= display.MaxX and maxx >= display.MinX and miny <= display.MaxY and maxy >= display.MinY

**Comment by BishopGIS** [comment]
Есть пример данных, на которых происходит падение.

**Comment by 4eRTuk** [comment]
@BishopGIS с RTree было много падений, но думаю в свете 3.0 не особо актуально что-то кардинально менять. Пришли данные, на которых падение есть.

**Comment by 4eRTuk** [comment]
Падение из-за того, что [в слое указана СК 4326](http://pam.aari.ru:8080/api/resource/106/feature/), а [фичи отдаются в 3857](http://pam.aari.ru:8080/api/resource/106/feature/). Еще напутан тип геометрий слоя.

**Comment by BishopGIS** [comment]
А как такое получилось? Все же через формбилдер создавалось, т.е. это ошибка ФормБилдера?

**Comment by 4eRTuk** [comment]
Похоже ФБ просто взял СК из НГВ. Посмотри что отдается по ссылкам через АПИ - как-то странно выходит.21:24, July 13, 2016, Dmitry Baryshnikov <notifications@github.com>:А как такое получилось? Все же через формбилдер создавалось, т.е. это ошибка ФормБилдера? —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by BishopGIS** [comment]
По поводу типа геометрии: http://pam.aari.ru:8080/api/component/pyramid/pkg_version отдает версию 2. Для второй версии все типы приводятся к мульти.

**Comment by BishopGIS** [comment]
Так проблема не в ФБ оказалась.
