### ISSUE TITLE
Приложение вылетает при идентификации объектов из слоя NGW

### ISSUE THREAD

**Issue by drnextgis** [nextgis/android_gisapp#454]
Вот на этом слое: http://rykovd.nextgis.com/resource/34. При загрузке слоя пишет, что поле `desc` запрещено и удалено, может в этом причина.

**Comment by BishopGIS** [comment]
```
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:47)
	at android.text.HtmlToSpannedConverter.convert(Html.java:435)
	at android.text.Html.fromHtml(Html.java:138)
	at android.text.Html.fromHtml(Html.java:101)
	at com.nextgis.mobile.fragment.AttributesFragment.getRow(AttributesFragment.java:355)
	at com.nextgis.mobile.fragment.AttributesFragment.setAttributes(AttributesFragment.java:316)
	at com.nextgis.mobile.fragment.AttributesFragment.onCreateView(AttributesFragment.java:147)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4744)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.StringReader.<init>(StringReader.java:47)
	at android.text.HtmlToSpannedConverter.convert(Html.java:442)
	at android.text.Html.fromHtml(Html.java:136)
	at android.text.Html.fromHtml(Html.java:99)
	at com.nextgis.mobile.fragment.AttributesFragment.getRow(AttributesFragment.java:355)
	at com.nextgis.mobile.fragment.AttributesFragment.setAttributes(AttributesFragment.java:316)
	at com.nextgis.mobile.fragment.AttributesFragment.onCreateView(AttributesFragment.java:147)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```
