### ISSUE TITLE
Crash on zip file import

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#481]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.nextgis.maplibui.service.LayerFillService$UnzipForm.execute(LayerFillService.java:489)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:253)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by 4eRTuk** [comment]
I think it's ngfp file.
