### ISSUE TITLE
Crash on nextgis.com import layer

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#482]
```
java.lang.IllegalStateException: Expected an int but was BOOLEAN
	at android.util.JsonReader.nextInt(JsonReader.java:512)
	at com.nextgis.maplib.util.NGWUtil.readNGWFeatureFields(NGWUtil.java:439)
	at com.nextgis.maplib.util.NGWUtil.readNGWFeature(NGWUtil.java:403)
	at com.nextgis.maplib.map.NGWVectorLayer.createFromNGW(NGWVectorLayer.java:508)
	at com.nextgis.maplibui.service.LayerFillService$NGWVectorLayerFillTask.execute(LayerFillService.java:673)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:253)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by 4eRTuk** [comment]
Есть пример данных?

**Comment by BishopGIS** [comment]
Я пролазил по логу - нет там адреса, только сервер. Надо добавить для отладки что бы при импорте адрес в лог писался.

**Comment by 4eRTuk** [comment]
Адрес должен писаться, если DEBUG включен.

**Comment by BishopGIS** [comment]
Debug включен - версия из феи. А полного адреса - нет.

**Comment by BishopGIS** [comment]
One more crash
```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NULL
	at android.util.JsonReader.expect(JsonReader.java:310)
	at android.util.JsonReader.beginObject(JsonReader.java:293)
	at com.nextgis.maplib.datasource.GeoGeometryFactory.fromJsonStream(GeoGeometryFactory.java:69)
	at com.nextgis.maplib.util.GeoJSONUtil.readGeoJSONFeature(GeoJSONUtil.java:484)
	at com.nextgis.maplib.util.GeoJSONUtil.createLayerFromGeoJSONStream(GeoJSONUtil.java:434)
	at com.nextgis.maplib.map.VectorLayer.createFromGeoJson(VectorLayer.java:396)
	at com.nextgis.maplibui.service.LayerFillService$VectorLayerFillTask.execute(LayerFillService.java:390)
	at com.nextgis.maplibui.service.LayerFillService$2.run(LayerFillService.java:253)
	at java.lang.Thread.run(Thread.java:841)
```
