### ISSUE TITLE
Crash on edit account

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#484]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
	at com.nextgis.maplibui.GISApplication.getAccountUrl(GISApplication.java:240)
	at com.nextgis.maplibui.activity.NGWSettingsActivity.addEditAccountAction(NGWSettingsActivity.java:516)
	at com.nextgis.maplibui.activity.NGWSettingsActivity.fillAccountPreferences(NGWSettingsActivity.java:288)
	at com.nextgis.maplibui.fragment.NGWSettingsFragment.onCreate(NGWSettingsFragment.java:50)
	at android.app.Fragment.performCreate(Fragment.java:2061)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:868)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
	at android.app.BackStackRecord.run(BackStackRecord.java:852)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5624)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by 4eRTuk** [comment]
Fix in 072e2f88ffb6cc789fbbd290b5ab30eb744cf9ac
