### ISSUE TITLE
Crash while reorder layers on map

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#495]
```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131689687, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1591)
	at android.widget.AbsListView.onLayout(AbsListView.java:2202)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1215)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2854)
	at android.view.View.layout(View.java:16655)
	at android.view.ViewGroup.layout(ViewGroup.java:5438)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5498)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by BishopGIS** [comment]
On new build same crash
```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131689687, class com.nextgis.mobile.fragment.ReorderedLayerViewAnimated) with Adapter(class com.nextgis.maplibui.fragment.LayersListAdapter)]
	at android.widget.ListView.layoutChildren(ListView.java:1544)
	at android.widget.AbsListView.onLayout(AbsListView.java:1994)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1215)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
```
