### ISSUE TITLE
Crash on draw

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#496]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
	at com.nextgis.maplib.map.LayerGroup.cancelDraw(LayerGroup.java:297)
	at com.nextgis.maplib.map.MapDrawable.cancelDraw(MapDrawable.java:318)
	at com.nextgis.maplib.map.MapDrawable.runDraw(MapDrawable.java:278)
	at com.nextgis.maplibui.mapui.MapView.drawMapDrawable(MapView.java:627)
	at com.nextgis.maplibui.mapui.MapView.onLayerAdded(MapView.java:588)
	at com.nextgis.maplib.map.MapEventSource$1.handleMessage(MapEventSource.java:314)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by BishopGIS** [comment]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
	at com.nextgis.maplib.map.LayerGroup.cancelDraw(LayerGroup.java:297)
	at com.nextgis.maplib.map.MapDrawable.cancelDraw(MapDrawable.java:318)
	at com.nextgis.maplib.map.MapDrawable.runDraw(MapDrawable.java:278)
	at com.nextgis.maplibui.mapui.MapView.drawMapDrawable(MapView.java:627)
	at com.nextgis.maplibui.mapui.MapView.onLayerAdded(MapView.java:588)
	at com.nextgis.maplib.map.MapEventSource$1.handleMessage(MapEventSource.java:314)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)

```
