### ISSUE TITLE
Crash on android 2.3.6

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#513]
```
java.lang.NoSuchMethodError: android.view.MenuItem.getActionView
	at com.nextgis.mobile.activity.MainActivity$1.run(MainActivity.java:352)
	at android.os.Handler.handleCallback(Handler.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3687)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)
```

abi	armeabi
abi2	unknown
apiLevel	10
board	torino
bootloader	unknown
brand	samsung
cpuCores	1
device	GT-S6102
deviceId	GINGERBREAD
deviceModel	GT-S6102
display	GINGERBREAD.XXMA1
isRoot	false
localeCountry	RU
localeLanguage	ru
manufacturer	samsung
memorySize	296360
osRelease	2.3.6
osVersion	2.6.35.7
product	GT-S6102
screenDensity	120
screenHeight	320
screenWidth	240
Disk Info 	
/sdcard 	1,779 MB / 3,716 MB

**Comment by trolleway** [comment]
Воспроизводится только на этом устройстве.
* Нажать кнопку рисования геометрии - для точечного или полигонального слоя
* На экране появляется маркер или треугольник  - но двигать по экрану его нельзя.
* Через несколько секунд стабильно приложение вылетает.

**Comment by 4eRTuk** [comment]
Судя по логу, крэш из-за крутящегося индикатора прорисовки карты был. @trolleway надо бы еще раз проверить будет воспроизводиться по описанной тобой схеме или нет.
