### ISSUE TITLE
Crash on pause

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#523]
Crash report for NextGIS Mobile 2.4.2 (18) #1

Message

Unable to pause activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41d29448

Stacktrace
```
java.lang.RuntimeException: Unable to pause activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41d29448
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3016)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2971)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2949)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1245)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5039)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41d29448
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:657)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1352)
	at android.hardware.SystemSensorManager.unregisterListenerImpl(SystemSensorManager.java:573)
	at android.hardware.SensorManager.unregisterListener(SensorManager.java:551)
	at com.nextgis.maplibui.fragment.CompassFragment.onPause(CompassFragment.java:209)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2253)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2157)
	at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:461)
	at com.nextgis.mobile.activity.MainActivity.onPause(MainActivity.java:778)
	at android.app.Activity.performPause(Activity.java:5206)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1236)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3002)
	... 12 more
```
Session data

Tester: User-1526
Started At: 2016-09-24 03:42:38
Duration: 00:00

Device data

OS: Android 4.2.1 - API 17
Device: MID - iDxD8 3G
Screen: 976 x 768 (160 dpi)

**Comment by BishopGIS** [comment]
Crash report for NextGIS Mobile 2.4.2 (18) #24

Message

java.lang.RuntimeException: Unable to pause activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41511a50

Stacktrace
```
java.lang.RuntimeException: Unable to pause activity {com.nextgis.mobile/com.nextgis.mobile.activity.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41511a50
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3016)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2971)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2949)
	at android.app.ActivityThread.access$800(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1245)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5039)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: android.hardware.SystemSensorManager$1@41511a50
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:657)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1352)
	at android.hardware.SystemSensorManager.unregisterListenerImpl(SystemSensorManager.java:573)
	at android.hardware.SensorManager.unregisterListener(SensorManager.java:551)
	at com.nextgis.maplibui.fragment.CompassFragment.onPause(CompassFragment.java:209)
	at android.support.v4.app.Fragment.performPause(Fragment.java:2253)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
	at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2157)
	at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
	at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:461)
	at com.nextgis.mobile.activity.MainActivity.onPause(MainActivity.java:778)
	at android.app.Activity.performPause(Activity.java:5206)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1236)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3002)
	... 12 more
```
Session data

Tester: User-1585
Started At: 2016-09-24 16:27:35
Duration: 00:40

Device data

OS: Android 4.2.1 - API 17
Device: MID - iDxD8 3G
Screen: 976 x 768 (160 dpi)
