### ISSUE TITLE
Crash on set new path for map(s)

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/android_gisapp#532]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.mobile/com.nextgis.mobile.activity.SettingsActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.Toolbar$SavedState
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
    at android.app.ActivityThread.access$800(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5333)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.Toolbar$SavedState
    at android.os.Parcel.readParcelableCreator(Parcel.java:2154)
    at android.os.Parcel.readParcelable(Parcel.java:2104)
    at android.os.Parcel.readValue(Parcel.java:2020)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
    at android.os.Parcel.readSparseArray(Parcel.java:1742)
    at android.os.Parcel.readValue(Parcel.java:2077)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
    at android.os.Bundle.unparcel(Bundle.java:249)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1818)
    at android.app.Dialog.onRestoreInstanceState(Dialog.java:439)
    at android.preference.DialogPreference.showDialog(DialogPreference.java:302)
    at com.nextgis.mobile.dialog.SelectMapPathDialogPreference.showDialog(SelectMapPathDialogPreference.java:136)
    at android.preference.DialogPreference.onRestoreInstanceState(DialogPreference.java:441)
    at com.nextgis.mobile.dialog.SelectMapPathDialogPreference.onRestoreInstanceState(SelectMapPathDialogPreference.java:117)
    at android.preference.Preference.dispatchRestoreInstanceState(Preference.java:1806)
    at android.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:337)
    at android.preference.Preference.restoreHierarchyState(Preference.java:1788)
    at android.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:194)
    at android.app.Fragment.performActivityCreated(Fragment.java:1708)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1853)
    at android.app.Activity.performCreate(Activity.java:5346)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
    ... 12 more
```

**Comment by 4eRTuk** [comment]
Какая версия Android? Есть шаги для воспроизведения?

**Comment by BishopGIS** [comment]
Android 	4.4.2
Но смущает:
Disk Info	
/sdcard	9,511 MB / 61,487 MB

Лог скинул на почту. Возможно там с системой что-то (ресурсов не хватает или еще чего).
